version: '2'
services:
  apache-php:
    image: trilations/symfony4
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    network_mode: host
    environment:
      APACHE_LOG_DIR: /var/www/html/logs
    